### PR TITLE
Accept arrays as the request data

### LINKED ISSUE #133: FormData and other xhr send types are converted to plain objects
FormData is a valid option for xhr requests and is useful for uploading files. In addition there are other types, like Blob that may be sent via xhr. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

If I have an xhr request like this:

```javascript
        const data = new FormData();
        for (let i = 0; i < files.length; i++) {
            data.append(i, files.item(i));
        }

            const req = new XMLHttpRequest();
            req.open('POST', this.properties.url, true);
            req.onload = function () {
                if (req.status === 200) {
                    resolve(JSON.parse(req.responseText));
                } else {
                    reject(req);
                }
            };
            req.onerror = reject;
            req.send(data);
```

The fixture `request` variable does not allow accessing the FormData properties and fails with 
```
// throws error TypeError: 'entries' called on an object that does not implement interface FormData.
```

The solution is something like checking to see of the data is an instance of the various data types that can be passed to `send`. Will submit a pr to demonstrate.

### PR DESCRIPTION
**Pull request by chasenlehara**
This makes it so you can send an array as the data for a request and can-fixture won’t turn it into an object.

Closes https://github.com/canjs/can-fixture/issues/133

### CODE REVIEW

File: test/fixture_test.js [hunk 1]
```diff
@@ -1864,22 +1898,4 @@ if ("onabort" in XMLHttpRequest._XHR.prototype) {
...
-		var data = new FormData();
-		var xhr = new XMLHttpRequest();
-		xhr.addEventListener('load', function() {
-			fixture('/upload', null);
-			ok(true, 'should not throw when sending FormData');
-			start();
-		});
-		xhr.open('POST', '/upload', true);
-		xhr.send(data);
-	});
```
Comment (chasenlehara) [inline test/fixture_test.js:1884]: I don’t think this test should’ve been wrapped in the `"onabort" in XMLHttpRequest._XHR.prototype` check.

File: core.js [hunk 2]
```diff
@@ -27,14 +28,6 @@ var methodMapping = {
...
 };
 
-
-// Get a global reference.
-var GLOBAL = typeof global !== "undefined"? global : window;
-
-// valid form types in addition to plain objects as URL search params
-// https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send
-var formTypes = ['ArrayBuffer', 'ArrayBufferView', 'Blob', 'FormData'];
-
```
Comment (chasenlehara) [inline core.js:37]: This change basically switches from explicitly checking for different types (ArrayBuffer, FormData, etc.) to checking for plain objects vs. everything else.

**Comment by matthewp** [comment]
lgtm
